### ISSUE TITLE
Traceback (most recent call last): 

### ISSUE THREAD

**Issue by mindjek007** [abhira0/dbscr#1]
appreciate your work :)

python run.py -s https://scrolller.com/r/Blep
Traceback (most recent call last):
  File "C:\Users\user\Downloads\dbscr-main\run.py", line 2, in <module>
    from dbdl.magoosh import MAG_D, MAG_H, MAG_IDM
  File "C:\Users\user\Downloads\dbscr-main\dbdl\magoosh\__init__.py", line 1, in <module>
    from .downloader import Downloader as MAG_D
  File "C:\Users\user\Downloads\dbscr-main\dbdl\magoosh\downloader.py", line 6, in <module>
    from pyrhd.utility.cprint import aprint, deleteLines, printInfo
ImportError: cannot import name 'deleteLines' from 'pyrhd.utility.cprint' (C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyrhd\utility\cprint.py)

**Comment by abhira0** [comment]
Could you please try upgrading pyrhd?
I have updated the custom pyrhd package and uploaded into pypi.org today!!

`pip install pyrhd --upgrade`

**Comment by jameswebb07** [comment]
After upgrade pyrhd 

C:\Users\user\Downloads\dbscr-main>python run.py -s https://scrolller.com/r/Blep
Sub name: Blep
←[38;5;99m
>>>←[39m ←[38;5;201mHarvester
←[39m
←[38;5;99m[←[39m←[38;5;201mi←[39m←[38;5;99m] ←[39m←[38;2;78;201;176mHarvester←[39m ←[38;5;105mfor←[39m ←[35mhttps://scrolller.com/r/Blep←[39m ←[38;5;105mhas been instantiated←[39m
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyrhd\harvester\hrv8r.py", line 39, in getFileData
    raise Exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Downloads\dbscr-main\run.py", line 65, in <module>
    SLR(a)
  File "C:\Users\user\Downloads\dbscr-main\run.py", line 18, in SLR
    SLR_H(sub_name, DOWNLOAD_PATH, "info") if not a.noharvest else None
  File "C:\Users\user\Downloads\dbscr-main\dbdl\scrolller\harvester.py", line 39, in __init__
    super().__init__(ultimatum_path, SAVING_INTERVAL, self.ultimatum)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyrhd\harvester\hrv8r.py", line 21, in __init__
    self.getFileData(default_ultimatum)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyrhd\harvester\hrv8r.py", line 42, in getFileData
    os.makedirs(p, exist_ok=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'F:\\'
